### ISSUE TITLE
Game Adder Listing Error

### ISSUE THREAD

**Issue by Gam3rsInStinCt** [hetelek/Velocity#42]
I tried to add a game, but when I try to open it I come up with an error message.
"The listing could not be parsed. Try again later as the servers may be down and make sure Velocity has access to the internet"
Here is a picture of it:
http://gyazo.com/b1afeecbe527c799f271592fb49c6a76

Velocity has access to the internet, and it is fully updated. I don't know what else I can do. Is this a bug?

**Comment by jdjesje** [comment]
I'm having the same problem now

**Comment by Default-xex** [comment]
Hetelek, plz help me! After yours recents updates i cant add any game to my Profile, i get this Game Adder Listing Error! My Velocity has access to the internet, and it is fully updated

**Comment by Chronos136** [comment]
The Game Adder won't work again, its telling me that the listing cannot be parsed, am i doing something wrong?

**Comment by bailemahl** [comment]
same here

**Comment by Aldrinklassen** [comment]
Same thing happens on my side
