### ISSUE TITLE
Flash Drive Problem

### ISSUE THREAD

**Issue by RaZrXDarkness** [hetelek/Velocity#73]
I plug in my flash drive (completely) and I open up velocity, but when I choose "Raw Device Viewer" a blank screen pops up (It shows the format of the flash drive being read in the program, but doesn't load at all) (Here is an image of what my flash drive looks like   http://ecx.images-amazon.com/images/I/41VpyrvQvJL._SY300_.jpg)

**Comment by landaire** [comment]
See #72.
