### ISSUE TITLE
Game Adder Listing Error after Recents Updates

### ISSUE THREAD

**Issue by Default-xex** [hetelek/Velocity#76]
Hetelek, plz help me! After yours recents updates i cant add any game to my Profile, i get this Game Adder Listing Error! My Velocity has access to the internet, and it is fully updated!

Here is a picture of it:
http://gyazo.com/b1afeecbe527c799f271592fb49c6a76

**Comment by hetelek** [comment]
We did not pay for hosting this year. The game adder will probably not be available again.

**Comment by Default-xex** [comment]
Ok, thx 4 the great work in Velocity.. :)

**Comment by Cj-Malone** [comment]
@hetelek Any chance I can get the domain? I'd be happy to host this.

**Comment by Kayasuz** [comment]
> @hetelek Any chance I can get the domain? I'd be happy to host this.

@hetelek could u make him a hoster??

**Comment by Experiment5X** [comment]
Actually some scummy company bought the domain and is selling it for like
$1k so unless you want to buy it for the much we’re all SOL.

**Comment by hetelek** [comment]
Yeah sorry about that. If you get a new domain and open a PR we can approve. Maybe we can just put everything on AWS S3 and just use the S3 subdomain. Recompiling this thing might be a struggle though.

Seems like important code is also commented out: https://github.com/hetelek/Velocity/commit/97a2c3224643f97870fb12dd02efd03c6f8d616e

**Comment by Cj-Malone** [comment]
As it stands the domain expires on 2020-10-23, and if they don't renew I was going to buy it. I wasn't planning on any maintenance, cpp isn't my thing, I was purely going to re create the game adder server, I've already got [most 360 GPDs](https://360.keepawayfromfire.co.uk/) and I'll get the remainder when I've got some free time.

The benefit of getting the domain over an update is that old versions of Velocity would continue to work, although I don't expect Velocity has a big install base any more.

**Comment by Kayasuz** [comment]
> As it stands the domain expires on 2020-10-23, and if they don't renew I was going to buy it. I wasn't planning on any maintenance, cpp isn't my thing, I was purely going to re create the game adder server, I've already got [most 360 GPDs](https://360.keepawayfromfire.co.uk/) and I'll get the remainder when I've got some free time.
> 
> The benefit of getting the domain over an update is that old versions of Velocity would continue to work, although I don't expect Velocity has a big install base any more.

@Cj-Malone Good to hear that! any update please reply here :)

**Comment by Cj-Malone** [comment]
The domain was extended for an extra year, so I that's not gonna happen. To be honest I've lost interest in this again anyway.
